---
# tasks file for install-ingress-nginx
- name: Install pip package
  apt:
    state: present
    update_cache: yes
    pkg:
    - python3-pip

- name: Install kubernetes python package
  pip:
    name: kubernetes
    
- name: Create ingress-nginx namespace
  become: no 
  kubernetes.core.k8s:
    name: ingress-nginx 
    api_version: v1
    kind: Namespace
    state: present

- name: Add ingress-nginx repo
  become: no
  kubernetes.core.helm_repository:
    name: ingress-nginx
    repo_url: https://kubernetes.github.io/ingress-nginx

- name: Install ingress-nginx
  become: no
  kubernetes.core.helm:
    name: ingress-nginx
    chart_ref: "ingress-nginx/ingress-nginx"
    release_namespace: ingress-nginx
    values:
      hostNetwork: true
      hostPort:
        enabled: true
