---
# tasks file for install-ingress-nginx
- name: Add ingress-nginx repo
  kubernetes.core.helm_repository:
    name: ingress-nginx
    repo_url: https://kubernetes.github.io/ingress-nginx

- name: Install ingress-nginx
  kubernetes.core.helm:
    create_namespace: true
    namespace: ingress-nginx
    name: ingress-nginx
    chart_ref: "ingress-nginx/ingress-nginx"
    values:
      controller:
        service:
          nodePorts:
            http: "{{ ingress_http_port }}"
            https: "{{ ingress_ssl_port }}"

- name: Wait for ingress pods to be running 
  shell: "kubectl wait --for=condition=Ready --timeout=600s --all pods -n ingress-nginx"

