---
# tasks file for install-metallb
- name: Add metallb repo
  kubernetes.core.helm_repository:
    name: metallb
    repo_url: https://metallb.github.io/metallb

- name: Install metallb
  kubernetes.core.helm:
    wait: yes
    create_namespace: true
    name: metallb
    chart_ref: "metallb/metallb"
    namespace: metallb-system

- name: Wait for metallb pods to be created
  shell: "kubectl wait --for=condition=Ready --timeout=600s --all pods -n metallb-system"

- name: Create metallb pool
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: metallb.io/v1beta1
      kind: IPAddressPool
      metadata:
        name: main-pool
        namespace: metallb-system
      spec:
        addresses:
        - "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}/32"

- name: Create custom resource
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: metallb.io/v1beta1
      kind: L2Advertisement
      metadata:
        name: main-pool
        namespace: metallb-system
      spec:
        ipAddressPools:
        - main-pool
        nodeSelectors:
        - matchLabels:
            kubernetes.io/hostname: "{{ inventory_hostname }}"
