- name: Update and install docker packages
  apt:
    update_cache: yes
    #cache_valid_time: 3600
    state: latest
    pkg:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release

- name: Create keyrings directory
  file:
    path: /etc/apt/keyrings
    state: directory

- name: Get the docker key
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /tmp/docker_key

- name: Dearmor the docker key
  # only run the shell command because apt_key command is depreciated
  shell: "gpg --dearmor < /tmp/docker_key > /etc/apt/keyrings/docker.gpg"
  changed_when: false

- name: Add docker official GPG key
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present

- name: Install containerd runtime
  apt:
    update_cache: yes
    state: present
    pkg:
    - containerd.io

- name: Make containerd directory
  file:
    path: /etc/containerd
    state: directory

- name: Get containerd config
  command: "containerd config default"
  register: containerd_config
  changed_when: false

- name: Create config.toml
  copy:
    remote_src: yes
    content: "{{containerd_config.stdout}}"
    dest: /etc/containerd/config.toml
    force: yes
  changed_when: false

- name: Set systemd cgroup in config.toml
  replace:
    path: /etc/containerd/config.toml
    regexp: "SystemdCgroup = false"
    replace: "SystemdCgroup = true"

- name: Set systemd cgroup in config.toml
  replace:
    path: /etc/containerd/config.toml
    regexp: '^disabled_plugins = \["cri"\]'
    replace: 'disabled_plugins = []'

- name: Enable and start containerd
  service:
    name: containerd
    enabled: yes
    state: restarted
